backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
site_url: https://ghccglobal.org
logo_url: https://ghccglobal.org/static/church-svg-57b3a1c59fba7c068b98dfb882b2c3af.svg

media_folder: "Gloryhills/src/datalogs/images"
public_folder: "/Gloryhills/src/datalogs/images"

collections:
  - name: "events"
    label: "Event Updates"
    folder: "Gloryhills/src/datalogs/events"
    delete: true
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    summary: "{{title}} - {{date}}"
    fields:
      - { label: "Query", name: "query", widget: "select", options: ["Events"], default: ["Events"] }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["Upcoming Events", "Events Calendar", "University Outreaches"]}
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }

  - name: "youtube_sermons"
    label: "Youtube Sermons"
    folder: "Gloryhills/src/datalogs/y_sermons"
    create: true
    delete: true
    slug: "{{slug}}"
    identifier_field: "title"
    summary: "{{title}} - {{date}}"
    fields:
      - { label: "Query", name: "query", widget: "select", options: ["youtube_sermon"], default: ["youtube_sermon"] }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Youtube Link", name: "externalLink", widget: "text" }
  
  - name: "spotify_sermons"
    label: "Spotify Sermons"
    folder: "Gloryhills/src/datalogs/s_sermons"
    create: true
    delete: true
    slug: "{{slug}}"
    identifier_field: "title"
    summary: "{{title}} - {{date}}"
    fields:
      - { label: "Query", name: "query", widget: "select", options: ["spotify_sermon"], default: ["spotify_sermon"] }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Spotify Link", name: "externalLink", widget: "text" }
